const {app,BrowserWindow,ipcMain,dialog}=require("electron");
const {spawn,execFile}=require("child_process");
const path=require("path");
let currentProcess=null;
function createWindow(){const win=new BrowserWindow({width:1120,height:820,minWidth:850,minHeight:650,backgroundColor:"#0b1020",webPreferences:{preload:path.join(__dirname,"preload.js"),contextIsolation:true,nodeIntegration:false}});win.loadFile("index.html")}
function runCommand(command,args){return new Promise((resolve,reject)=>{execFile(command,args,{windowsHide:true,maxBuffer:4*1024*1024},(error,stdout,stderr)=>error?reject(Object.assign(error,{stdout,stderr})):resolve({stdout,stderr}))})}
function duration(s){if(!Number.isFinite(s))return "";const h=Math.floor(s/3600),m=Math.floor(s%3600/60),sec=Math.floor(s%60);return h?h+":"+String(m).padStart(2,"0")+":"+String(sec).padStart(2,"0"):m+":"+String(sec).padStart(2,"0")}
function progress(line){const p=line.match(/(\d+(?:\.\d+)?)%/),sp=line.match(/at\s+([^\s]+\/s)/),eta=line.match(/ETA\s+([^\s]+)/);return{percent:p?parseFloat(p[1]):0,speed:sp?sp[1]:"",eta:eta?eta[1]:"",status:/100%/.test(line)?"finished":"downloading"}}
function buildArgs(job){const o=job.options||{},a=["--newline","--no-color"];if(!o.playlist)a.push("--no-playlist");if(o.mode==="audio")a.push("-x","--audio-format",o.audioFormat||"mp3","--audio-quality",o.audioQuality||"0");else if(o.mode==="custom")a.push("-f",o.formatCode||"bv*+ba/b");else{const f=o.resolution&&o.resolution!=="best"?"bv*[height<="+o.resolution+"]+ba/b[height<="+o.resolution+"]/b":"bv*+ba/b";a.push("-f",f,"--merge-output-format",o.container||"mp4")}a.push("-o",path.join(o.outputPath||app.getPath("downloads"),"%(title)s.%(ext)s"));if(o.subtitles)a.push("--write-subs","--sub-langs","all");if(o.autoSubs)a.push("--write-auto-subs");if(o.thumbnail)a.push("--embed-thumbnail");if(o.metadata)a.push("--embed-metadata");if(o.archive)a.push("--download-archive",path.join(app.getPath("userData"),"download-archive.txt"));if(o.proxy)a.push("--proxy",o.proxy);if(o.rateLimit)a.push("--limit-rate",o.rateLimit);if(o.fragments)a.push("--concurrent-fragments",String(o.fragments));if(o.retries)a.push("--retries",String(o.retries));if(o.cookies)a.push("--cookies-from-browser",o.cookies);if(o.extraArgs){const extra=o.extraArgs.match(/(?:[^\s"]+|"[^"]*")+/g)||[];a.push(...extra.map(x=>x.replace(/^"|"$/g,"")))}a.push("--",job.url);return a}
ipcMain.handle("check-tools",async()=>{const check=async n=>{try{const r=await runCommand(n,["--version"]);return r.stdout.trim()||r.stderr.trim()}catch{return null}};return{ytDlp:!!(await check("yt-dlp")),ffmpeg:!!(await check("ffmpeg"))}});
ipcMain.handle("choose-folder",async e=>{const r=await dialog.showOpenDialog(BrowserWindow.fromWebContents(e.sender),{properties:["openDirectory"]});return r.canceled?null:r.filePaths[0]});
ipcMain.handle("get-info",async(e,{url,options})=>{try{const a=["--dump-single-json","--no-warnings"];if(!options?.playlist)a.push("--no-playlist");a.push("--",url);const r=await runCommand("yt-dlp",a),i=JSON.parse(r.stdout);return{ok:true,title:i.title,uploader:i.uploader,durationText:duration(i.duration),formats:(i.formats||[]).length}}catch(err){return{ok:false,error:(err.stderr||err.stdout||err.message||"解析失敗").trim()}}});
ipcMain.handle("cancel-download",()=>{if(currentProcess){currentProcess.kill();currentProcess=null}return true});
ipcMain.handle("start-download",(e,job)=>new Promise(resolve=>{const win=BrowserWindow.fromWebContents(e.sender),a=buildArgs(job);win.webContents.send("download-log","\n$ yt-dlp "+a.map(x=>/\s/.test(x)?JSON.stringify(x):x).join(" ")+"\n");currentProcess=spawn("yt-dlp",a,{windowsHide:true});let buf="";const data=c=>{buf+=c.toString();const lines=buf.split(/\r?\n/);buf=lines.pop()||"";for(const line of lines){if(!line.trim())continue;win.webContents.send("download-log",line);if(/%/.test(line))win.webContents.send("download-progress",progress(line))}};currentProcess.stdout.on("data",data);currentProcess.stderr.on("data",data);currentProcess.on("error",err=>{currentProcess=null;win.webContents.send("download-log",err.message);resolve({ok:false,error:err.message})});currentProcess.on("close",code=>{currentProcess=null;const ok=code===0;win.webContents.send("download-complete",{message:ok?"下載完成":"下載失敗或已取消"});resolve({ok,error:ok?null:"exit code "+code})})}));
app.whenReady().then(createWindow);app.on("window-all-closed",()=>{if(process.platform!=="darwin")app.quit()});app.on("activate",()=>{if(BrowserWindow.getAllWindows().length===0)createWindow()});